---
- name: apt upgrade cache and autoclean autoremove 
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
    autoremove: yes
    install_recommends: no
  notify: restart server

- name: Perform apt full-upgrade
  become: true
  apt:
    upgrade: full
  notify: restart server

- name: Install required packages
  apt:
    name: "{{ required_packages }}"
    state: latest
  notify: restart server
