# hardenning specific to raspberry pi
- name: Setup Admin Group
  group:
    name: admin
    state: present

- name: Create ansible user
  user: 
    name: "{{ server_user_name }}"
    password: "{{ server_user_name | password_hash('md5') }}"
    shell: /bin/bash
    groups: admin
    update_password: on_create

- name: add Admin Group to sudoers
  copy:
    dest: /etc/sudoers.d/admin-group
    content: "%admin ALL=(ALL) NOPASSWD:ALL"
    force: yes
    group: root
    owner: root
    mode: 0440
    follow: yes

- name: Add authorized keys for user
  authorized_key:
    user: "{{ server_user_name }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ user_public_keys }}"

- name: sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sshd

- name: Allow http/https with UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "80"
    - "443"

- name: Allow SSH from admin network or from particular IP
  ufw:
    rule: allow
    src: "{{ item }}"
    port: 22
    proto: tcp
  with_items:
    - "{{ admin_net }}"

- name: Enable ufw
  ufw:
    state: enabled
    direction: incoming
    policy: deny
    logging: low

- name: send to syslog server via rsyslog
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @@{{ log_host }}:{{ log_port }}"

- name: Remove pi user from sudo group
  command: deluser pi sudo
  ignore_errors: yes

- name: Remove pi user from sudoers.d folder
  file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd 

- name: disablefs.conf
  file:
    state: touch
    path: /etc/modprobe.d/disablefs.conf
    owner: root
    group: root
    mode: 0644

- name: disable file system kearnel modules
  lineinfile:
    dest: /etc/modprobe.d/disablefs.conf
    line: "install {{ item }} /bin/true"
  with_items:
    - "{{ fs_modules_blacklist }}"

- name: disable ctrl-alt-del
  systemd:
    name: ctrl-alt-del.target
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: Password settings
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS 90"
    state: present

- name: Set Password Expiration Days
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS 7"
    state: present

- name: Set Default umask for Users
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "UMASK"
    line: "UMASK 077"
    state: present

- name: disable ctrl-alt-del
  systemd:
    name: ctrol-alt-del.target
    masked: 'yes'
    enabled: 'no'
    state: stopped

---
