# hardenning specific to raspberry pi
- name: Setup Admin Group
  group:
    name: admin
    state: present

- name: Create ansible user
  user: 
    name: "{{ server_user_name }}"
    password: "{{ server_user_name | password_hash('md5') }}"
    shell: /bin/bash
    groups: admin
    update_password: on_create

- name: add Admin Group to sudoers
  copy:
    dest: /etc/sudoers.d/admin-group
    content: "%admin ALL=(ALL) NOPASSWD:ALL"
    force: yes
    group: root
    owner: root
    mode: 0440
    follow: yes

- name: Add authorized keys for user
  authorized_key:
    user: "{{ server_user_name }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ user_public_keys }}"

- name: Remove root ssh access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart ssh

- name: Disallow password authentication ssh
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh

- name: Allow ssh and http/https with UFW
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ ufw_allowed_ports }}"

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny

- name: Remove pi user from sudo group
  command: deluser pi sudo
  ignore_errors: yes

- name: Remove pi user  from sudoers.d folder
  file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd

