---
server_user_name: kiosk_admin

server_user_password: raspberry

autostart_user: pi

required_packages:
  - ufw
  - chromium-browser
  - unclutter
  - lxde
  - python3-pip
  - needrestart
  - debsecan
  - debsums
  - fail2ban
  - debian-goodies
  - rkhunter

timezone: America/Chicago

user_public_keys: ~/.ssh/ansible_id.pub

admin_net: 172.16.1.0/24

log_host: loghost.example.com

log_port: 512

fs_modules_blacklist:
  - cramfs
  - freevxfs
  - hfs
  - hfsplus
  - jffs2
  - squashfs
  - udf
  - vfat

ssh_allow_groups: admin

ssh_max_auth_tries: 2

ssh_max_sessions: 2
